services:
  db:
    image: postgres:14.17
    container_name: db
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"

  app:
    image: jvnlee/test-booking-system-app:latest
    container_name: app
    restart: always
    depends_on:
      - db
    env_file:
      - .env
    ports:
      - "8000:8000"