"""remove_reservation_status_rejected_value_from_reservation

Revision ID: 2fbfdfbe647f
Revises: 7a8c1bcfdeed
Create Date: 2025-03-04 04:47:36.830099

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2fbfdfbe647f'
down_revision: Union[str, None] = '7a8c1bcfdeed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
