"""change_column_name_time_to_date_time_in_test_schedules

Revision ID: 7a8c1bcfdeed
Revises: 706ffc794c43
Create Date: 2025-03-03 07:42:47.746709

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7a8c1bcfdeed'
down_revision: Union[str, None] = '706ffc794c43'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('test_schedules', sa.Column('date_time', sa.DateTime(), nullable=False))
    op.drop_constraint('test_schedules_time_key', 'test_schedules', type_='unique')
    op.create_unique_constraint(None, 'test_schedules', ['date_time'])
    op.drop_column('test_schedules', 'time')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('test_schedules', sa.Column('time', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'test_schedules', type_='unique')
    op.create_unique_constraint('test_schedules_time_key', 'test_schedules', ['time'])
    op.drop_column('test_schedules', 'date_time')
    # ### end Alembic commands ###
