"""add_reservation_status_column

Revision ID: e6aab7191b1f
Revises: 14eb67026f3d
Create Date: 2025-03-03 04:01:57.770721

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e6aab7191b1f'
down_revision: Union[str, None] = '14eb67026f3d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reservations', sa.Column('status', sa.Enum('REQUESTED', 'CONFIRMED', 'REJECTED', 'CANCELLED', name='reservationstatus', native_enum=False), nullable=False))
    op.drop_column('reservations', 'is_confirmed')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reservations', sa.Column('is_confirmed', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('reservations', 'status')
    # ### end Alembic commands ###
